#!/usr/bin/env bash

# Define the directories to search
dirs_to_search=(
    ~/projects
    ~
    ~/work
    ~/Desktop
)

# Filter only existing directories
existing_dirs=()
for dir in "${dirs_to_search[@]}"; do
    if [[ -d "$dir" ]]; then
        existing_dirs+=("$dir")
    fi
done

# Use fzf to select a directory
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${existing_dirs[@]}" -mindepth 1 -maxdepth 2 -type d | fzf)
fi

# Exit if no directory is selected
if [[ -z "$selected" ]]; then
    exit 0
fi

# Handle spaces in the selected directory
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"

